#!/bin/bash
pkgname=cartesi-machine-emulator
pkgver=0.19.0
pkgrel=1
_pkgver=${pkgver}-test2
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/machine-emulator/archive/refs/tags/v${_pkgver}.tar.gz"
         "debian/patches/add-generated-files.diff::https://github.com/cartesi/machine-emulator/releases/download/v${_pkgver}/add-generated-files.diff")
sha256sums=("a188a9af51afc15e2b2c72eb4e835bb8114e493d92aecdac6888d55345944abd  ${pkgname}_${pkgver}.orig.tar.gz"
            "a892e2d9f5c331f5e80bcb5db4133e7db625aa4d14ffdf9467b75c4c34d1744f  debian/patches/add-generated-files.diff")
arch=any

prepare() {
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv machine-emulator-${_pkgver} ${pkgname}-${pkgver}
    patch -d ${pkgname}-${pkgver} -Np1 < debian/patches/add-generated-files.diff
}
