#!/bin/bash
pkgname=cartesi-machine-emulator
pkgver=0.19.0
pkgrel=1
_pkgver=${pkgver}-test1
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/machine-emulator/archive/refs/tags/v${_pkgver}.tar.gz"
         "debian/patches/add-generated-files.diff::https://github.com/cartesi/machine-emulator/releases/download/v${_pkgver}/add-generated-files.diff")
sha256sums=("93121d1c7edf5ebc8d5b8b042d3b18a4cf2454c702ec2cfe8c92086d7529e16d  ${pkgname}_${pkgver}.orig.tar.gz"
            "162d62ec8b66801f1ad421774050ea1d6c5cc4c7dcc8f5615956853d6baed87f  debian/patches/add-generated-files.diff")
arch=any

prepare() {
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv machine-emulator-${_pkgver} ${pkgname}-${pkgver}
    patch -d ${pkgname}-${pkgver} -Np1 < debian/patches/add-generated-files.diff
}
