#!/bin/bash
pkgname=cartesi-machine-rootfs-image
pkgver=0.20.0
pkgrel=1
_pkgver=${pkgver}-test1
sources=("rootfs.ext2::https://github.com/cartesi/machine-rootfs-image/releases/download/v${_pkgver}/rootfs-ubuntu.ext2")
sha256sums="a38dbf39bdadc644bb31f1fc427be037b3082c9007afe1d9f2220b20d2789271 rootfs.ext2"
arch=all

prepare() {
    # Create reproducible source tarball
    mkdir ${pkgname}-${pkgver}
    mv rootfs.ext2 ${pkgname}-${pkgver}/
    tar --sort=name \
        --mtime="@$(stat -c %Y ${pkgname}-${pkgver}/rootfs.ext2)" \
        --owner=0 --group=0 --numeric-owner \
        --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
        -czf ${pkgname}_${pkgver}.orig.tar.gz ${pkgname}-${pkgver}
}
