#!/bin/bash
pkgname=cartesi-machine-rootfs-image
pkgver=0.17.0
pkgrel=1
_pkgver=${pkgver}-test1
sources=("rootfs.ext2::https://github.com/cartesi/machine-guest-tools/releases/download/v${_pkgver}/rootfs-tools-v${_pkgver}.ext2")
sha256sums="6ca4073504bbc3e42cfda7641bb66aed1e0cd5122146544869b49aa09befe01e rootfs.ext2"
arch=all

prepare() {
    # Create reproducible source tarball
    mkdir ${pkgname}-${pkgver}
    mv rootfs.ext2 ${pkgname}-${pkgver}/
    tar --sort=name \
        --mtime="@$(stat -c %Y ${pkgname}-${pkgver}/rootfs.ext2)" \
        --owner=0 --group=0 --numeric-owner \
        --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
        -czf ${pkgname}_${pkgver}.orig.tar.gz ${pkgname}-${pkgver}
}
